// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyDTQALzB02bgCu9EckAkHNdBRz82XT-s',
    appId: '1:957071578348:web:3002e48b34948192f541c9',
    messagingSenderId: '957071578348',
    projectId: 'loginauthentication-c7ebe',
    authDomain: 'loginauthentication-c7ebe.firebaseapp.com',
    storageBucket: 'loginauthentication-c7ebe.appspot.com',
    measurementId: 'G-5P2GLMZF54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOgKAd5R1lGugzZts1podGGVIX4ppZSfc',
    appId: '1:957071578348:android:71964abd39069b9df541c9',
    messagingSenderId: '957071578348',
    projectId: 'loginauthentication-c7ebe',
    storageBucket: 'loginauthentication-c7ebe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz3iaTAdkoXid5Ic_8ECAA4MFwszSeLNY',
    appId: '1:957071578348:ios:b7b7fcf61c80ef38f541c9',
    messagingSenderId: '957071578348',
    projectId: 'loginauthentication-c7ebe',
    storageBucket: 'loginauthentication-c7ebe.appspot.com',
    iosClientId: '957071578348-scs85eeabb965n6p89rlfbp54d36jq6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
